### PR TITLE
#64 Add Authors and updated README.md

### PR DESCRIPTION
**Pull request by stunstunstun**
- https://github.com/stunstunstun/awesome-wiki/issues/64 Add Authors
- https://github.com/stunstunstun/awesome-wiki/issues/65 Update README.md for updating

### CODE REVIEW

**Review by Ailrun — APPROVED** [review]

**Comment by Ailrun** [comment]
Fixes 나 resolves 같이 설명을 달면 Merge 되었을 때 issue 가 자동으로 닫힙니다.

**Comment by Ailrun** [comment]
예시:
Resolve #65

**Comment by stunstunstun** [comment]
@Ailrun 아주 좋은 팁입니다!

**Comment by Ailrun** [comment]
@stunstunstun https://help.github.com/articles/closing-issues-using-keywords/ 참고하세요

**Pull request merged**
